use crate::ast::{Ident, Lit};
use crate::core_ast::*;

/// Generate a standalone Rust program that evaluates `expr` and prints the result.
/// This is intentionally "boring": we embed a small runtime + evaluator.
pub fn emit_rust_program(expr: &CoreExpr) -> String {
    let mut out = String::new();

    out.push_str(r#"// AUTO-GENERATED by axis-core (Step 6)
// Standalone Rust program.

use std::collections::HashMap;
use std::rc::Rc;

#[derive(Clone)]
#[allow(dead_code)]
enum Value {
    Int(i64),
    Bool(bool),
    Unit,
    Tuple(Vec<Value>),
    Closure(Rc<dyn Fn(Value) -> Value>),
}

impl std::fmt::Debug for Value {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Value::Int(n) => write!(f, "{}", n),
            Value::Bool(b) => write!(f, "{}", b),
            Value::Unit => write!(f, "()"),
            Value::Tuple(xs) => {
                f.write_str("(")?;
                for (i, x) in xs.iter().enumerate() {
                    if i > 0 {
                        f.write_str(", ")?;
                    }
                    write!(f, "{:?}", x)?;
                }
                if xs.len() == 1 {
                    f.write_str(",")?;
                }
                f.write_str(")")
            }
            Value::Closure(_) => f.write_str("<closure>"),
        }
    }
}

type Env = HashMap<String, Value>;

#[allow(dead_code)]
fn proj(v: Value, idx: usize) -> Value {
    match v {
        Value::Tuple(xs) => {
            let i = idx.checked_sub(1).expect("projection index is 1-based");
            xs.get(i).cloned().expect("invalid projection index")
        }
        _ => panic!("projection on non-tuple"),
    }
}

// --- Embedded CoreExpr as Rust functions ---

fn eval_expr(env: &Env) -> Value {
"#);

    out.push_str("    let _env: &Env = env;\n");

    // Emit the expression as a Rust *expression*.
    // Important: do not generate `return` inside nested blocks, otherwise
    // evaluation returns from `eval_expr` too early.
    out.push_str("    ");
    out.push_str(&emit_expr_inline(expr, "_env"));

    out.push_str(
        r#"
}

fn main() {
    let env: Env = Env::new();
    let v = eval_expr(&env);
    println!("{:?}", v);
}
"#,
    );

    out
}

fn emit_expr_inline(expr: &CoreExpr, env: &str) -> String {
    match expr {
        CoreExpr::Seq { first, then } => format!(
            "{{ let _ = {}; {} }}",
            emit_expr_inline(first, env),
            emit_expr_inline(then, env)
        ),

        CoreExpr::LetIn { name, value, body, .. } => {
            let n = &name.0;
            format!(
                "{{ let v = {}; let mut env2: Env = {}.clone(); env2.insert(\"{}\".to_string(), v); let _env: &Env = &env2; {} }}",
                emit_expr_inline(value, env),
                env,
                escape_str(n),
                emit_expr_inline(body, "_env")
            )
        }

        CoreExpr::If { cond, then_br, else_br } => format!(
            "{{ let c = {}; match c {{ Value::Bool(true) => {{ {} }}, Value::Bool(false) => {{ {} }}, _ => panic!(\"non-bool condition\"), }} }}",
            emit_expr_inline(cond, env),
            emit_expr_inline(then_br, env),
            emit_expr_inline(else_br, env)
        ),

        CoreExpr::Lambda { param, body } => {
            let p = &param.name.0;
            format!(
                "{{ let captured: Env = {}.clone(); Value::Closure(Rc::new(move |arg: Value| {{ let mut env2: Env = captured.clone(); env2.insert(\"{}\".to_string(), arg); let _env: &Env = &env2; {} }})) }}",
                env,
                escape_str(p),
                emit_expr_inline(body, "_env")
            )
        }

        CoreExpr::App { head, args } => {
            if args.is_empty() {
                return emit_expr_inline(head, env);
            }

            let mut s = String::new();
            s.push_str("{ let f = ");
            s.push_str(&emit_expr_inline(head, env));
            s.push_str("; ");

            for (i, a) in args.iter().enumerate() {
                s.push_str(&format!("let a{} = {}; ", i, emit_expr_inline(a, env)));
                s.push_str(&format!(
                    "let f = match f {{ Value::Closure(c) => (c)(a{}), _ => panic!(\"not a function\") }}; ",
                    i
                ));
            }

            s.push_str("f }");
            s
        }

        CoreExpr::Atom(a) => emit_atom_value(a, env),
    }
}

fn emit_atom_value(a: &CoreAtom, env: &str) -> String {
    let mut base = match &a.base {
        CoreAtomBase::Lit(l) => emit_lit(l),
        CoreAtomBase::Var(Ident(name)) => {
            format!(r#"{}.get("{}").cloned().expect("unbound var")"#, env, escape_str(name))
        }
        CoreAtomBase::Tuple(xs) => {
            let parts: Vec<String> = xs.iter().map(|e| emit_expr_inline(e, env)).collect();
            format!("Value::Tuple(vec![{}])", parts.join(", "))
        }
        CoreAtomBase::Paren(e) => emit_expr_inline(e, env),
    };

    for idx in &a.projs {
        base = format!("proj({}, {})", base, idx);
    }
    base
}

fn emit_lit(l: &Lit) -> String {
    match l {
        Lit::Int(n) => format!("Value::Int({})", n),
        Lit::Bool(b) => format!("Value::Bool({})", b),
        Lit::Unit => "Value::Unit".to_string(),
    }
}

fn escape_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
