use crate::core_ast::*;
use crate::ast::{Ident, Lit};

/// Generate a standalone Rust program that evaluates `expr` and prints the result.
/// This is intentionally "boring": we embed a small runtime + evaluator.
pub fn emit_rust_program(expr: &CoreExpr) -> String {
    let mut out = String::new();

    out.push_str(r#"// AUTO-GENERATED by axis-core (Step 6)
// Standalone Rust program.

use std::collections::HashMap;
use std::rc::Rc;

#[derive(Debug, Clone, PartialEq, Eq)]
enum Value {
    Int(i64),
    Bool(bool),
    Unit,
    Tuple(Vec<Value>),
    Closure(Rc<dyn Fn(Value) -> Value>),
}

type Env = HashMap<String, Value>;

fn proj(mut v: Value, idx: usize) -> Value {
    match v {
        Value::Tuple(xs) => {
            let i = idx.checked_sub(1).expect("projection index is 1-based") ;
            xs.get(i).cloned().expect("invalid projection index")
        }
        _ => panic!("projection on non-tuple"),
    }
}

// --- Embedded CoreExpr as Rust functions ---

fn eval_expr(env: &Env) -> Value {
"#);

    // Emit the expression as Rust statements ending with a `return <Value>;`
    let body = emit_expr(expr, 1);
    out.push_str(&body);

    out.push_str(r#"
}

fn main() {
    let env: Env = Env::new();
    let v = eval_expr(&env);
    println!("{:?}", v);
}
"#);

    out
}

/// Emit code that evaluates `expr` and returns a `Value`.
/// `indent` is indentation level (4 spaces per level).
fn emit_expr(expr: &CoreExpr, indent: usize) -> String {
    match expr {
        CoreExpr::LetIn { name, value, body, .. } => {
            // let v0 = <value>;
            // let mut env1 = env.clone(); env1.insert("x", v0);
            // { evaluate body with env1 }
            let n = &name.0;
            let mut s = String::new();
            s.push_str(&indentln(indent, "{"));
            s.push_str(&indentln(indent + 1, &format!("let v = {};", emit_expr_value(value, indent + 1))));
            s.push_str(&indentln(indent + 1, "let mut env2 = env.clone();"));
            s.push_str(&indentln(indent + 1, &format!(r#"env2.insert("{}".to_string(), v);"#, escape_str(n))));
            s.push_str(&indentln(indent + 1, "{"));
            s.push_str(&indentln(indent + 2, "let env = &env2;"));
            s.push_str(&emit_expr(body, indent + 2));
            s.push_str(&indentln(indent + 1, "}"));
            s.push_str(&indentln(indent, "}"));
            s
        }

        CoreExpr::If { cond, then_br, else_br } => {
            let mut s = String::new();
            s.push_str(&indentln(indent, "{"));
            s.push_str(&indentln(indent + 1, &format!("let c = {};", emit_expr_value(cond, indent + 1))));
            s.push_str(&indentln(indent + 1, "match c {"));
            s.push_str(&indentln(indent + 2, "Value::Bool(true) => {"));
            s.push_str(&emit_expr(then_br, indent + 3));
            s.push_str(&indentln(indent + 2, "}"));
            s.push_str(&indentln(indent + 2, "Value::Bool(false) => {"));
            s.push_str(&emit_expr(else_br, indent + 3));
            s.push_str(&indentln(indent + 2, "}"));
            s.push_str(&indentln(indent + 2, "_ => panic!(\"non-bool condition\"),"));
            s.push_str(&indentln(indent + 1, "}"));
            s.push_str(&indentln(indent, "}"));
            s
        }

        CoreExpr::Lambda { param, body } => {
            // Return a Value::Closure that captures `env` (clone).
            // param is a single Value; bind it in a new env and eval body.
            let p = &param.name.0;
            let mut s = String::new();
            s.push_str(&indentln(indent, "{"));
            s.push_str(&indentln(indent + 1, "let captured = env.clone();"));
            s.push_str(&indentln(
                indent + 1,
                &format!(
                    r#"return Value::Closure(Rc::new(move |arg: Value| {{
    let mut env2 = captured.clone();
    env2.insert("{}".to_string(), arg);
    let env = &env2;
{}    }}
)));"#,
                    escape_str(p),
                    emit_expr_as_return(body, 1) // emits "return ..." with internal indentation
                ),
            ));
            s.push_str(&indentln(indent, "}"));
            s
        }

        CoreExpr::App { head, args } => {
            // Evaluate head, then each arg, apply sequentially (curried)
            let mut s = String::new();
            s.push_str(&indentln(indent, "{"));
            s.push_str(&indentln(indent + 1, &format!("let mut f = {};", emit_expr_value(head, indent + 1))));
            for (i, a) in args.iter().enumerate() {
                s.push_str(&indentln(indent + 1, &format!("let a{} = {};", i, emit_expr_value(a, indent + 1))));
                s.push_str(&indentln(indent + 1, &format!("f = match f {{ Value::Closure(c) => (c)(a{}), _ => panic!(\"not a function\") }};", i)));
            }
            s.push_str(&indentln(indent + 1, "return f;"));
            s.push_str(&indentln(indent, "}"));
            s
        }

        CoreExpr::Atom(a) => {
            let mut s = String::new();
            s.push_str(&indentln(indent, "{"));
            s.push_str(&indentln(indent + 1, &format!("return {};", emit_atom_value(a))));
            s.push_str(&indentln(indent, "}"));
            s
        }
    }
}

/// Emit a CoreExpr as a Rust expression of type Value (no statements).
fn emit_expr_value(expr: &CoreExpr, indent: usize) -> String {
    match expr {
        CoreExpr::Atom(a) => emit_atom_value(a),
        _ => {
            // For complex expressions, emit a block that evaluates and yields a Value.
            // We call the statement-emitter and ensure it returns.
            let mut s = String::new();
            s.push_str("{\n");
            s.push_str(&indent_str(indent + 1));
            s.push_str("let env = env;\n");
            s.push_str(&emit_expr_as_return(expr, indent + 1));
            s.push_str(&indent_str(indent));
            s.push_str("}\n");
            s
        }
    }
}

/// Emit code that ends with `return <Value>;` for an expression.
fn emit_expr_as_return(expr: &CoreExpr, indent: usize) -> String {
    // Reuse emit_expr(), which already uses return paths, but we need consistent indentation.
    // We wrap it in a function-ish block style.
    let mut s = String::new();
    // create a fake evaluation scope:
    // { ...; return <val>; }
    // emit_expr already returns with `return ...;` in branches.
    s.push_str(&emit_expr(expr, indent));
    // Ensure we don't fall through: if emit_expr didn’t return (it always does), panic.
    s.push_str(&indentln(indent, "panic!(\"fell through\");"));
    s
}

fn emit_atom_value(a: &CoreAtom) -> String {
    let mut base = match &a.base {
        CoreAtomBase::Lit(l) => emit_lit(l),
        CoreAtomBase::Var(Ident(name)) => format!(r#"env.get("{}").cloned().expect("unbound var")"#, escape_str(name)),
        CoreAtomBase::Tuple(xs) => {
            let parts: Vec<String> = xs.iter().map(|e| emit_expr_value(e, 0)).collect();
            format!("Value::Tuple(vec![{}])", parts.join(", "))
        }
        CoreAtomBase::Paren(e) => emit_expr_value(e, 0),
    };

    for idx in &a.projs {
        base = format!("proj({}, {})", base, idx);
    }
    base
}

fn emit_lit(l: &Lit) -> String {
    match l {
        Lit::Int(n) => format!("Value::Int({})", n),
        Lit::Bool(b) => format!("Value::Bool({})", b),
        Lit::Unit => "Value::Unit".to_string(),
    }
}

fn indent_str(level: usize) -> String {
    "    ".repeat(level)
}

fn indentln(level: usize, line: &str) -> String {
    format!("{}{}\n", indent_str(level), line)
}

fn escape_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
